CREATE TABLE IF NOT EXISTS hits (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY,
    app          VARCHAR(255) NOT NULL,
    uri          VARCHAR(255) NOT NULL,
    ip           VARCHAR(45) NOT NULL,
    request_time TIMESTAMP NOT NULL,

    CONSTRAINT hits_pk PRIMARY KEY (id)
);