CREATE TABLE IF NOT EXISTS users
(
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY,
    name                VARCHAR(100) NOT NULL,
    email               VARCHAR(100) NOT NULL,

    CONSTRAINT users_pk PRIMARY KEY (id),
    CONSTRAINT unique_user_email UNIQUE (email)
);


CREATE TABLE IF NOT EXISTS categories
(
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY,
    name                VARCHAR(50) NOT NULL,

    CONSTRAINT categories_pk PRIMARY KEY (id),
    CONSTRAINT unique_category_name UNIQUE (name)
);


CREATE TABLE IF NOT EXISTS events
(
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY,
    title               VARCHAR(100) NOT NULL,
    annotation          VARCHAR(175) NOT NULL,
    description         VARCHAR(250),
    created             TIMESTAMP,
    event_date          TIMESTAMP NOT NULL,
    published           TIMESTAMP,
    category_id         BIGINT NOT NULL,
    initiator_id        BIGINT NOT NULL,
    lat                 DOUBLE NOT NULL,
    lon                 DOUBLE NOT NULL,
    paid                BOOLEAN,
    participant_limit   INT DEFAULT 0,
    request_moderation  BOOLEAN DEFAULT TRUE,
    state               VARCHAR(20),
    confirmed_requests  INT,
    views               INT,

    CONSTRAINT events_pk PRIMARY KEY (id),

    CONSTRAINT events_category_fk FOREIGN KEY (category_id) REFERENCES categories (id),
    CONSTRAINT events_initiator_fk FOREIGN KEY (initiator_id) REFERENCES users (id),

    CONSTRAINT events_date_chk CHECK (event_date > CURRENT_TIMESTAMP)
);


CREATE TABLE IF NOT EXISTS requests
(
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY,
    event_id            BIGINT NOT NULL,
    requester_id        BIGINT NOT NULL,
    created             TIMESTAMP NOT NULL,
    status              VARCHAR(20),

    CONSTRAINT participation_requests_pk PRIMARY KEY (id),

    CONSTRAINT requests_event_fk FOREIGN KEY (event_id) REFERENCES events (id),
    CONSTRAINT requests_users_fk FOREIGN KEY (requester_id) REFERENCES users (id)
);


CREATE TABLE IF NOT EXISTS compilations
(
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY,
    title               VARCHAR(50) NOT NULL,
    pinned              BOOLEAN NOT NULL,

    CONSTRAINT compilations_pk PRIMARY KEY (id)
);


CREATE TABLE IF NOT EXISTS compilation_events
(
    compilation_id BIGINT NOT NULL,
    event_id BIGINT NOT NULL,

    CONSTRAINT compilation_events_compilation_fk FOREIGN KEY (compilation_id) REFERENCES compilations (id) ON DELETE CASCADE,
    CONSTRAINT compilation_events_event_fk FOREIGN KEY (event_id) REFERENCES events (id) ON DELETE CASCADE,

    CONSTRAINT unique_pair UNIQUE (compilation_id, event_id)
);